# Generated by Django 5.2 on 2025-05-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_alter_perfilusuario_fecha_nacimiento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='email_usuario',
        ),
    ]
