# Generated by Django 5.2 on 2025-05-24 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0003_remove_perfilusuario_email_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='nombre_usuario',
            field=models.CharField(default='', max_length=50),
        ),
    ]
