# Generated by Django 5.2 on 2025-05-24 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0005_sucursal_pedido_detallepedido_pedidokiosko_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='codigo',
            field=models.CharField(blank=True, max_length=12, null=True, unique=True),
        ),
    ]
