# Generated by Django 5.2 on 2025-05-25 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0006_pedido_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
