# Generated by Django 5.2 on 2025-05-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0008_pedido_puntos_ganados'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='puntos_usados',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
