# Generated by Django 5.2 on 2025-05-24 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(max_length=100)),
                ('tamaño', models.CharField(max_length=20)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=8)),
                ('tipo', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
            },
        ),
        migrations.CreateModel(
            name='BebidaCaliente',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.producto')),
                ('tipo_vaso', models.CharField(max_length=20)),
                ('tipo_leche', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
            ],
            bases=('menu.producto',),
        ),
        migrations.CreateModel(
            name='BebidaFria',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.producto')),
                ('tipo_vaso', models.CharField(max_length=20)),
                ('tipo_hielo', models.CharField(max_length=30)),
                ('sabor', models.CharField(max_length=30)),
            ],
            bases=('menu.producto',),
        ),
        migrations.CreateModel(
            name='Bocadillo',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.producto')),
                ('tipo_pan', models.CharField(max_length=30)),
                ('relleno', models.TextField()),
            ],
            bases=('menu.producto',),
        ),
        migrations.CreateModel(
            name='Reposteria',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.producto')),
                ('tipo_reposteria', models.CharField(max_length=30)),
                ('glaseado', models.BooleanField(default=False)),
                ('decorado', models.BooleanField(default=False)),
                ('sabor', models.CharField(max_length=30)),
            ],
            bases=('menu.producto',),
        ),
        migrations.CreateModel(
            name='Snack',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='menu.producto')),
                ('tipo_snack', models.CharField(max_length=30)),
                ('tipo_sabor', models.CharField(max_length=30)),
            ],
            bases=('menu.producto',),
        ),
    ]
