# Generated by Django 5.2 on 2025-05-25 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0002_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='puntos_extra',
            field=models.PositiveIntegerField(default=0, help_text='Puntos extra por comprar este producto'),
        ),
    ]
