# Generated by Django 5.2 on 2025-11-23 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('menu', '0003_producto_puntos_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoRelacionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(default=0.0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('producto_principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_relacionados', to='menu.producto')),
                ('producto_relacionado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_que_lo_relacionan', to='menu.producto')),
            ],
            options={
                'indexes': [models.Index(fields=['producto_principal'], name='sistema_rec_product_09ae6c_idx'), models.Index(fields=['producto_relacionado'], name='sistema_rec_product_664f7f_idx')],
                'unique_together': {('producto_principal', 'producto_relacionado')},
            },
        ),
    ]
