# Generated by Django 5.2 on 2025-05-24 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DireccionFacturacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=100, verbose_name='Razón social')),
                ('rfc', models.CharField(max_length=13, verbose_name='RFC')),
                ('calle', models.CharField(max_length=100, verbose_name='Calle')),
                ('numero_exterior', models.CharField(max_length=10, verbose_name='Número exterior')),
                ('numero_interior', models.CharField(blank=True, max_length=10, null=True, verbose_name='Número interior')),
                ('colonia', models.CharField(max_length=50)),
                ('municipio', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=50)),
                ('pais', models.CharField(default='México', max_length=50)),
                ('cp', models.CharField(max_length=10, verbose_name='Código Postal')),
                ('telefono_facturacion', models.CharField(max_length=15, verbose_name='Teléfono de facturación')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='direcciones_facturacion', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
